
all: etape3
	javac CalculatriceRPN.java


etape1:
	javac element.java

etape2: etape1
	javac Operation.java
	javac Chiffre_reel.java

etape3: etape2
	javac SaisieRPN.java
	javac MoteurRPN.java

rm_executable_java: 
	rm *.class


effacer ses traces:
	rm makefile
